version: "3.8"

services:
  wikijs-db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - node.hostname == wikijs-db

  wikijs-app-1:
    image: requarks/wiki:2
    depends_on:
      - wikijs-db
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.hostname == wikijs-app-1

  wikijs-app-2:
    image: requarks/wiki:2
    depends_on:
      - wikijs-db
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.hostname == wikijs-app-2

  wikijs-lb:
    image: nginx:1.25-alpine
    depends_on:
      - wikijs-app-1
      - wikijs-app-2
    ports:
      - "8080:80"
    volumes:
      - /home/dallasdesimone/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      placement:
        constraints:
          - node.hostname == wikijs-lb