version: "3.8"

services:
  wikijs-db:
    image: postgres:16
    container_name: wikijs-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbdata: